"""First migration

Revision ID: 135f4e98ce2e
Revises: 
Create Date: 2025-03-11 20:22:15.628020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '135f4e98ce2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=True),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('chat_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('words',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('banned_words', sa.String(), nullable=True),
    sa.Column('punishment', sa.String(), nullable=True),
    sa.Column('ban_time', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banned',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('banned_id', sa.BIGINT(), nullable=True),
    sa.Column('banned_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('chats')
    op.drop_table('words')
    op.drop_table('banned')
    # ### end Alembic commands ###
