from aiogram_dialog.widgets.text import Const, Format
from aiogram_dialog.widgets.input import TextInput, MessageInput, ManagedTextInput
from aiogram_dialog.widgets.kbd import Button, Select, SwitchTo, Url, Column, Radio, ScrollingGroup
from aiogram_dialog import Dialog, DialogManager, StartMode, Window
from bot.dialogs.start.states import FirstDialogSG
from aiogram.enums import ContentType
from bot.dialogs.start.getters import (getter_for_fifth, get_chats, get_i18n, get_words_ban_list, get_languages, getter_str_chat,
                      get_users_ban_list)
from bot.dialogs.start.handlers import (correct_text, check_correct_word, chat_choice, choose_punish, error_time_text, no_text, ban_word_choice, \
    final_confirm, choose_user_ban_time, check_correct_ban_time, correct_ban_time_input, radio_lang_state_changed, error_words_text,
                       unban_user)

first_dialog=Dialog(
    Window(
Format('{hello_user}'),
        SwitchTo(
            text=Format('{select_chat}'),
            id='next_button_1',
            state=FirstDialogSG.choose_chat),
        Url(Format('{add_bot}'),
            id='add_bot',
            url=Const('https://t.me/message_filter_vvv_bot?startgroup=start')),
        SwitchTo(
            text=Format('{change_lang}'),
            id='go',
            state=FirstDialogSG.choose_lang),
        state=FirstDialogSG.start
    ),
    Window(
        Format('{choose_lang}'),
        Column(
            Radio(
                checked_text=Format('🔘 {item[0]}'),
                unchecked_text=Format('⚪️ {item[0]}'),
                item_id_getter=lambda x: x[1],
                id='choose_lang',
                items='languages',
                on_click=radio_lang_state_changed
            ),
        ),
        SwitchTo(
            text=Format('{back}'),
            id='go',
            state=FirstDialogSG.start
        ),
        state=FirstDialogSG.choose_lang,
        getter=get_languages
    ),
    Window(
    Format('{yours_chats}'),
        ScrollingGroup(
            Select(
            Format('{item[0]}'),
            id='ch',
            item_id_getter=lambda x: x[1],
            items='chats_of_user',
            on_click=chat_choice
            ),
            id='scroll_chats',
            width=1,
            height=8,
            hide_on_single_page=True
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_1',
            state=FirstDialogSG.start
        ),
        state=FirstDialogSG.choose_chat,
        getter=get_chats
    ),
    Window(
        Format('{choose_chat_action}'),
        SwitchTo(text=Format('{add_ban_words}'),
                 id='add_ban_words',
                 state=FirstDialogSG.input_ban_words
        ),
        SwitchTo(text=Format('{show_ban_list}'),
                 id='show_ban_list',
                 state=FirstDialogSG.ban_words_list
        ),
        SwitchTo(text=Format('{banned_ids_list}'),
                 id='banned_ids_list',
                 state=FirstDialogSG.banned_ids_list
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_2',
            state=FirstDialogSG.choose_chat
        ),
        state=FirstDialogSG.chat_actions,
    getter=getter_str_chat
    ),
    Window(
        Format('{input_words}'),
        TextInput(id='ban_words_input',
                  type_factory=check_correct_word,
                  on_success=correct_text,
                  on_error=error_words_text),
        MessageInput(
            func=no_text,
            content_types=ContentType.ANY
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_2',
            state=FirstDialogSG.chat_actions
        ),
        state=FirstDialogSG.input_ban_words
    ),
    Window(
        Format('{your_ban_list}'),
        ScrollingGroup(
            Select(
            Format('{item[0]}'),
            id='words_ban_list',
            item_id_getter=lambda x: x[1],
            items='words_ban_list',
            on_click=ban_word_choice
            ),
            id='scroll_words',
            width=1,
            height=8,
            hide_on_single_page=True
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_1',
            state=FirstDialogSG.chat_actions
        ),
        state=FirstDialogSG.ban_words_list,
        getter=get_words_ban_list
    ),
    Window(
        Format('{banned_people_window}'),
        ScrollingGroup(
            Select(
            Format('{item[0]}'),
            id='users_ban_list',
            item_id_getter=lambda x: x[1],
            items='users_ban_list',
            on_click=unban_user
            ),
            id='scroll',
            width=1,
            height=10,
            hide_on_single_page=True
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_1',
            state=FirstDialogSG.chat_actions
        ),
        state=FirstDialogSG.banned_ids_list,
        getter=get_users_ban_list
    ),
    Window(
        Format('{choose_punishment}'),
        SwitchTo(
            Format('{delete_messages}'),
            id='delete_messages',
            on_click=choose_punish,
            state=FirstDialogSG.final_confirm
        ),
        SwitchTo(
            Format('{ban_user}'),
            id='ban_user',
            on_click=choose_punish,
            state=FirstDialogSG.choose_user_ban_time
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_3',
            state=FirstDialogSG.input_ban_words
        ),
        state=FirstDialogSG.choose_punishment
    ),
    Window(
        Format('{choose_user_ban_time}'),
        Column(
            SwitchTo(
                text=Format('{five_min}'),
                id='5',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                ),
                SwitchTo(
                text=Format('{thirty_min}'),
                id='30',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                ),
                SwitchTo(
                text=Format('{one_hour}'),
                id='60',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                ),
                SwitchTo(
                text=Format('{one_day}'),
                id='3600',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                ),
                SwitchTo(
                text=Format('{seven_days}'),
                id='25200',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                ),
                SwitchTo(
                text=Format('{thirty_days}'),
                id='108000',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                ),
                SwitchTo(
                text=Format('{forever}'),
                id='0',
                on_click=choose_user_ban_time,
                state=FirstDialogSG.final_confirm
                )
        ),
        TextInput(id='ban_time_input',
                  type_factory=check_correct_ban_time,
                  on_success=correct_ban_time_input,
                  on_error=error_time_text),
        MessageInput(
            func=no_text,
            content_types=ContentType.ANY
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_3',
            state=FirstDialogSG.choose_punishment
        ),
        state=FirstDialogSG.choose_user_ban_time
    ),
    Window(
Format('{full_confirm}'),
        SwitchTo(
            Format('{confirm}'),
            id='finish',
            state=FirstDialogSG.chat_actions,
            on_click=final_confirm
        ),
        SwitchTo(
            text=Format('{back}'),
            id='back_button_4',
            state=FirstDialogSG.choose_punishment
        ),
        state=FirstDialogSG.final_confirm,
        getter=getter_for_fifth
    ),
    getter=get_i18n
)