services:
  #app:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  restart: unless-stopped
  #  env_file: ".env"
  #  command: ["python", "-m", "bot"]
  #  depends_on:
  #    - nats
  #    - postgres

  nats:
    image: nats:2.10.22
    restart: unless-stopped
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"
    env_file:
      - '.env'
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_USER=superuser
      - POSTGRES_DB=data

    volumes:
      - "postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    env_file:
      - '.env'
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres
volumes:
  pgadmin:
  postgres: